BOX_IMAGE = "ubuntu/trusty64"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
    end
  end
end